/**
 * Chat entity definitions — these are generated by Prisma but we define them
 * locally to avoid hard dependencies on @prisma/client exports that may not
 * be regenerated in all environments.
 */

export interface ChatRoom {
  id: string;
  courseId: string;
  createdAt: Date;
}

export interface ChatMessage {
  id: string;
  content: string;
  roomId: string;
  senderId: string;
  deletedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export enum EnrollmentStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
