export const COUNTRIES: { code: string; name: string; flag: string }[] = [
  { code: 'AF', name: 'Афганистан', flag: '🇦🇫' },
  { code: 'AL', name: 'Албания', flag: '🇦🇱' },
  { code: 'DZ', name: 'Алжир', flag: '🇩🇿' },
  { code: 'AD', name: 'Андорра', flag: '🇦🇩' },
  { code: 'AO', name: 'Ангола', flag: '🇦🇴' },
  { code: 'AG', name: 'Антигуа и Барбуда', flag: '🇦🇬' },
  { code: 'AR', name: 'Аргентина', flag: '🇦🇷' },
  { code: 'AM', name: 'Армения', flag: '🇦🇲' },
  { code: 'AU', name: 'Австралия', flag: '🇦🇺' },
  { code: 'AT', name: 'Австрия', flag: '🇦🇹' },
  { code: 'AZ', name: 'Азербайджан', flag: '🇦🇿' },
  { code: 'BS', name: 'Багамы', flag: '🇧🇸' },
  { code: 'BH', name: 'Бахрейн', flag: '🇧🇭' },
  { code: 'BD', name: 'Бангладеш', flag: '🇧🇩' },
  { code: 'BB', name: 'Барбадос', flag: '🇧🇧' },
  { code: 'BY', name: 'Беларусь', flag: '🇧🇾' },
  { code: 'BE', name: 'Бельгия', flag: '🇧🇪' },
  { code: 'BZ', name: 'Белиз', flag: '🇧🇿' },
  { code: 'BJ', name: 'Бенин', flag: '🇧🇯' },
  { code: 'BT', name: 'Бутан', flag: '🇧🇹' },
  { code: 'BO', name: 'Боливия', flag: '🇧🇴' },
  { code: 'BA', name: 'Босния и Герцеговина', flag: '🇧🇦' },
  { code: 'BW', name: 'Ботсвана', flag: '🇧🇼' },
  { code: 'BR', name: 'Бразилия', flag: '🇧🇷' },
  { code: 'BN', name: 'Бруней', flag: '🇧🇳' },
  { code: 'BG', name: 'Болгария', flag: '🇧🇬' },
  { code: 'BF', name: 'Буркина-Фасо', flag: '🇧🇫' },
  { code: 'BI', name: 'Бурунди', flag: '🇧🇮' },
  { code: 'CV', name: 'Кабо-Верде', flag: '🇨🇻' },
  { code: 'KH', name: 'Камбоджа', flag: '🇰🇭' },
  { code: 'CM', name: 'Камерун', flag: '🇨🇲' },
  { code: 'CA', name: 'Канада', flag: '🇨🇦' },
  { code: 'CF', name: 'ЦАР', flag: '🇨🇫' },
  { code: 'TD', name: 'Чад', flag: '🇹🇩' },
  { code: 'CL', name: 'Чили', flag: '🇨🇱' },
  { code: 'CN', name: 'Китай', flag: '🇨🇳' },
  { code: 'CO', name: 'Колумбия', flag: '🇨🇴' },
  { code: 'KM', name: 'Коморы', flag: '🇰🇲' },
  { code: 'CG', name: 'Конго', flag: '🇨🇬' },
  { code: 'CD', name: 'ДР Конго', flag: '🇨🇩' },
  { code: 'CR', name: 'Коста-Рика', flag: '🇨🇷' },
  { code: 'HR', name: 'Хорватия', flag: '🇭🇷' },
  { code: 'CU', name: 'Куба', flag: '🇨🇺' },
  { code: 'CY', name: 'Кипр', flag: '🇨🇾' },
  { code: 'CZ', name: 'Чехия', flag: '🇨🇿' },
  { code: 'DK', name: 'Дания', flag: '🇩🇰' },
  { code: 'DJ', name: 'Джибути', flag: '🇩🇯' },
  { code: 'DM', name: 'Доминика', flag: '🇩🇲' },
  { code: 'DO', name: 'Доминиканская Республика', flag: '🇩🇴' },
  { code: 'EC', name: 'Эквадор', flag: '🇪🇨' },
  { code: 'EG', name: 'Египет', flag: '🇪🇬' },
  { code: 'SV', name: 'Сальвадор', flag: '🇸🇻' },
  { code: 'GQ', name: 'Экваториальная Гвинея', flag: '🇬🇶' },
  { code: 'ER', name: 'Эритрея', flag: '🇪🇷' },
  { code: 'EE', name: 'Эстония', flag: '🇪🇪' },
  { code: 'SZ', name: 'Эсватини', flag: '🇸🇿' },
  { code: 'ET', name: 'Эфиопия', flag: '🇪🇹' },
  { code: 'FJ', name: 'Фиджи', flag: '🇫🇯' },
  { code: 'FI', name: 'Финляндия', flag: '🇫🇮' },
  { code: 'FR', name: 'Франция', flag: '🇫🇷' },
  { code: 'GA', name: 'Габон', flag: '🇬🇦' },
  { code: 'GM', name: 'Гамбия', flag: '🇬🇲' },
  { code: 'GE', name: 'Грузия', flag: '🇬🇪' },
  { code: 'DE', name: 'Германия', flag: '🇩🇪' },
  { code: 'GH', name: 'Гана', flag: '🇬🇭' },
  { code: 'GR', name: 'Греция', flag: '🇬🇷' },
  { code: 'GD', name: 'Гренада', flag: '🇬🇩' },
  { code: 'GT', name: 'Гватемала', flag: '🇬🇹' },
  { code: 'GN', name: 'Гвинея', flag: '🇬🇳' },
  { code: 'GW', name: 'Гвинея-Бисау', flag: '🇬🇼' },
  { code: 'GY', name: 'Гайана', flag: '🇬🇾' },
  { code: 'HT', name: 'Гаити', flag: '🇭🇹' },
  { code: 'HN', name: 'Гондурас', flag: '🇭🇳' },
  { code: 'HU', name: 'Венгрия', flag: '🇭🇺' },
  { code: 'IS', name: 'Исландия', flag: '🇮🇸' },
  { code: 'IN', name: 'Индия', flag: '🇮🇳' },
  { code: 'ID', name: 'Индонезия', flag: '🇮🇩' },
  { code: 'IR', name: 'Иран', flag: '🇮🇷' },
  { code: 'IQ', name: 'Ирак', flag: '🇮🇶' },
  { code: 'IE', name: 'Ирландия', flag: '🇮🇪' },
  { code: 'IL', name: 'Израиль', flag: '🇮🇱' },
  { code: 'IT', name: 'Италия', flag: '🇮🇹' },
  { code: 'JM', name: 'Ямайка', flag: '🇯🇲' },
  { code: 'JP', name: 'Япония', flag: '🇯🇵' },
  { code: 'JO', name: 'Иордания', flag: '🇯🇴' },
  { code: 'KZ', name: 'Казахстан', flag: '🇰🇿' },
  { code: 'KE', name: 'Кения', flag: '🇰🇪' },
  { code: 'KI', name: 'Кирибати', flag: '🇰🇮' },
  { code: 'KW', name: 'Кувейт', flag: '🇰🇼' },
  { code: 'KG', name: 'Киргизия', flag: '🇰🇬' },
  { code: 'LA', name: 'Лаос', flag: '🇱🇦' },
  { code: 'LV', name: 'Латвия', flag: '🇱🇻' },
  { code: 'LB', name: 'Ливан', flag: '🇱🇧' },
  { code: 'LS', name: 'Лесото', flag: '🇱🇸' },
  { code: 'LR', name: 'Либерия', flag: '🇱🇷' },
  { code: 'LY', name: 'Ливия', flag: '🇱🇾' },
  { code: 'LI', name: 'Лихтенштейн', flag: '🇱🇮' },
  { code: 'LT', name: 'Литва', flag: '🇱🇹' },
  { code: 'LU', name: 'Люксембург', flag: '🇱🇺' },
  { code: 'MG', name: 'Мадагаскар', flag: '🇲🇬' },
  { code: 'MW', name: 'Малави', flag: '🇲🇼' },
  { code: 'MY', name: 'Малайзия', flag: '🇲🇾' },
  { code: 'MV', name: 'Мальдивы', flag: '🇲🇻' },
  { code: 'ML', name: 'Мали', flag: '🇲🇱' },
  { code: 'MT', name: 'Мальта', flag: '🇲🇹' },
  { code: 'MH', name: 'Маршалловы Острова', flag: '🇲🇭' },
  { code: 'MR', name: 'Мавритания', flag: '🇲🇷' },
  { code: 'MU', name: 'Маврикий', flag: '🇲🇺' },
  { code: 'MX', name: 'Мексика', flag: '🇲🇽' },
  { code: 'FM', name: 'Микронезия', flag: '🇫🇲' },
  { code: 'MD', name: 'Молдова', flag: '🇲🇩' },
  { code: 'MC', name: 'Монако', flag: '🇲🇨' },
  { code: 'MN', name: 'Монголия', flag: '🇲🇳' },
  { code: 'ME', name: 'Черногория', flag: '🇲🇪' },
  { code: 'MA', name: 'Марокко', flag: '🇲🇦' },
  { code: 'MZ', name: 'Мозамбик', flag: '🇲🇿' },
  { code: 'MM', name: 'Мьянма', flag: '🇲🇲' },
  { code: 'NA', name: 'Намибия', flag: '🇳🇦' },
  { code: 'NR', name: 'Науру', flag: '🇳🇷' },
  { code: 'NP', name: 'Непал', flag: '🇳🇵' },
  { code: 'NL', name: 'Нидерланды', flag: '🇳🇱' },
  { code: 'NZ', name: 'Новая Зеландия', flag: '🇳🇿' },
  { code: 'NI', name: 'Никарагуа', flag: '🇳🇮' },
  { code: 'NE', name: 'Нигер', flag: '🇳🇪' },
  { code: 'NG', name: 'Нигерия', flag: '🇳🇬' },
  { code: 'NO', name: 'Норвегия', flag: '🇳🇴' },
  { code: 'OM', name: 'Оман', flag: '🇴🇲' },
  { code: 'PK', name: 'Пакистан', flag: '🇵🇰' },
  { code: 'PW', name: 'Палау', flag: '🇵🇼' },
  { code: 'PA', name: 'Панама', flag: '🇵🇦' },
  { code: 'PG', name: 'Папуа — Новая Гвинея', flag: '🇵🇬' },
  { code: 'PY', name: 'Парагвай', flag: '🇵🇾' },
  { code: 'PE', name: 'Перу', flag: '🇵🇪' },
  { code: 'PH', name: 'Филиппины', flag: '🇵🇭' },
  { code: 'PL', name: 'Польша', flag: '🇵🇱' },
  { code: 'PT', name: 'Португалия', flag: '🇵🇹' },
  { code: 'QA', name: 'Катар', flag: '🇶🇦' },
  { code: 'RO', name: 'Румыния', flag: '🇷🇴' },
  { code: 'RU', name: 'Россия', flag: '🇷🇺' },
  { code: 'RW', name: 'Руанда', flag: '🇷🇼' },
  { code: 'KN', name: 'Сент-Китс и Невис', flag: '🇰🇳' },
  { code: 'LC', name: 'Сент-Люсия', flag: '🇱🇨' },
  { code: 'VC', name: 'Сент-Винсент и Гренадины', flag: '🇻🇨' },
  { code: 'WS', name: 'Самоа', flag: '🇼🇸' },
  { code: 'SM', name: 'Сан-Марино', flag: '🇸🇲' },
  { code: 'ST', name: 'Сан-Томе и Принсипи', flag: '🇸🇹' },
  { code: 'SA', name: 'Саудовская Аравия', flag: '🇸🇦' },
  { code: 'SN', name: 'Сенегал', flag: '🇸🇳' },
  { code: 'RS', name: 'Сербия', flag: '🇷🇸' },
  { code: 'SC', name: 'Сейшелы', flag: '🇸🇨' },
  { code: 'SL', name: 'Сьерра-Леоне', flag: '🇸🇱' },
  { code: 'SG', name: 'Сингапур', flag: '🇸🇬' },
  { code: 'SK', name: 'Словакия', flag: '🇸🇰' },
  { code: 'SI', name: 'Словения', flag: '🇸🇮' },
  { code: 'SB', name: 'Соломоновы Острова', flag: '🇸🇧' },
  { code: 'SO', name: 'Сомали', flag: '🇸🇴' },
  { code: 'ZA', name: 'ЮАР', flag: '🇿🇦' },
  { code: 'SS', name: 'Южный Судан', flag: '🇸🇸' },
  { code: 'ES', name: 'Испания', flag: '🇪🇸' },
  { code: 'LK', name: 'Шри-Ланка', flag: '🇱🇰' },
  { code: 'SD', name: 'Судан', flag: '🇸🇩' },
  { code: 'SR', name: 'Суринам', flag: '🇸🇷' },
  { code: 'SE', name: 'Швеция', flag: '🇸🇪' },
  { code: 'CH', name: 'Швейцария', flag: '🇨🇭' },
  { code: 'SY', name: 'Сирия', flag: '🇸🇾' },
  { code: 'TW', name: 'Тайвань', flag: '🇹🇼' },
  { code: 'TJ', name: 'Таджикистан', flag: '🇹🇯' },
  { code: 'TZ', name: 'Танзания', flag: '🇹🇿' },
  { code: 'TH', name: 'Таиланд', flag: '🇹🇭' },
  { code: 'TL', name: 'Тимор-Лесте', flag: '🇹🇱' },
  { code: 'TG', name: 'Того', flag: '🇹🇬' },
  { code: 'TO', name: 'Тонга', flag: '🇹🇴' },
  { code: 'TT', name: 'Тринидад и Тобаго', flag: '🇹🇹' },
  { code: 'TN', name: 'Тунис', flag: '🇹🇳' },
  { code: 'TR', name: 'Турция', flag: '🇹🇷' },
  { code: 'TM', name: 'Туркменистан', flag: '🇹🇲' },
  { code: 'TV', name: 'Тувалу', flag: '🇹🇻' },
  { code: 'UG', name: 'Уганда', flag: '🇺🇬' },
  { code: 'UA', name: 'Украина', flag: '🇺🇦' },
  { code: 'AE', name: 'ОАЭ', flag: '🇦🇪' },
  { code: 'GB', name: 'Великобритания', flag: '🇬🇧' },
  { code: 'US', name: 'США', flag: '🇺🇸' },
  { code: 'UY', name: 'Уругвай', flag: '🇺🇾' },
  { code: 'UZ', name: 'Узбекистан', flag: '🇺🇿' },
  { code: 'VU', name: 'Вануату', flag: '🇻🇺' },
  { code: 'VE', name: 'Венесуэла', flag: '🇻🇪' },
  { code: 'VN', name: 'Вьетнам', flag: '🇻🇳' },
  { code: 'YE', name: 'Йемен', flag: '🇾🇪' },
  { code: 'ZM', name: 'Замбия', flag: '🇿🇲' },
  { code: 'ZW', name: 'Зимбабве', flag: '🇿🇼' },
]

/** Возвращает флаг + название страны по коду */
export function getCountryLabel(code: string | null | undefined): string {
  if (!code) return ''
  const c = COUNTRIES.find((x) => x.code === code)
  return c ? `${c.flag} ${c.name}` : code
}
